In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
wine = pd.read_csv('https://bit.ly/wine_csv_data')
data = wine[['alcohol', 'sugar', 'pH']]
target = wine['class']
train_input, test_input, train_target, test_target = train_test_split(data,target,test_size=0.2,random_state=42)

In [10]:
from sklearn.model_selection import cross_validate
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_jobs=-1, random_state=42)
scores = cross_validate(rf, train_input, train_target,return_train_score = True, n_jobs=1)
print(np.mean(scores['train_score']),np.mean(scores['test_score']))

0.9973541965122431 0.8905151032797809


In [11]:
rf.fit(train_input, train_target)
print(rf.feature_importances_)

[0.23167441 0.50039841 0.26792718]


In [12]:
rf = RandomForestClassifier(oob_score=True, n_jobs=-1, random_state=42)
rf.fit(train_input, train_target)
print(rf.oob_score_)

0.8934000384837406


In [19]:
from sklearn.ensemble import ExtraTreesClassifier
et = ExtraTreesClassifier(n_jobs=-1, random_state=42)
scores = cross_validate(et, train_input, train_target, return_train_score=True, n_jobs=1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9974503966084433 0.8887848893166506


In [20]:
#랜덤 포레스트와 비슷한 결과이지만 엑스트라 트리가 계산 속도가 더 빠르다

In [21]:
et.fit(train_input, train_target)
print(et.feature_importances_)

[0.20183568 0.52242907 0.27573525]


In [22]:
#엑스트라 트리의 회귀버전은 ExtraTreesRegressor 클래스이다.

In [24]:
#그레디언트 부스팅은 깊이가 얇은 결정 트리를 사용하여 이전 트리의 오차를 보완. => 경사 하강법을 사용하여 트리에 앙상블

In [27]:
from sklearn.ensemble import GradientBoostingClassifier
gb = GradientBoostingClassifier(random_state=42)
scores = cross_validate(gb, train_input, train_target, return_train_score=True, n_jobs=1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.8881086892152563 0.8720430147331015


In [28]:
#그레디언트 부스팅은 결정 트리의 개수를 늘려도 과대적합에 매우 강하다

In [30]:
gb = GradientBoostingClassifier(n_estimators=500, learning_rate=0.2,random_state=42)
scores = cross_validate(gb, train_input, train_target, return_train_score=True, n_jobs=1)
print(np.mean(scores['train_score']),np.mean(scores['test_score']))

0.9464595437171814 0.8780082549788999


In [ ]:
#결정트리의 개수를 500개로 5배나 늘려도 과대적합을 억제하고 있다.

In [31]:
gb.fit(train_input, train_target)
print(gb.feature_importances_)

[0.15882696 0.6799705  0.16120254]


In [32]:
#일반적으로 그레디언트 부스팅이 랜덤 포레스트 보다 조금 더 높은 성능을 보인다 하지만 속도가 느리다는 단점이 있다.

In [33]:
from sklearn.ensemble import HistGradientBoostingClassifier
hgb = HistGradientBoostingClassifier(random_state=42)
scores = cross_validate(hgb, train_input, train_target, return_train_score=True)
print(np.mean(scores['train_score']),np.mean(scores['test_score']))

0.9321723946453317 0.8801241948619236


In [34]:
#히스토그램 기반 그레이디언트 부스팅은 자체적으로 특성 중요도를 제공하지 않는다.
#그래서 permutation_importance()함수를 사용한다.

In [36]:
from sklearn.inspection import permutation_importance

hgb.fit(train_input, train_target)
result = permutation_importance(hgb, train_input, train_target, n_repeats=10, random_state=42, n_jobs=1)
print(result.importances_mean)

[0.08876275 0.23438522 0.08027708]


In [37]:
#permutation_importance()함수가 반환하는 객체는 반복하여 얻은 특성 중요도, 평균, 표준 편차를 담고 있다.

In [38]:
result = permutation_importance(hgb, test_input, test_target, n_repeats=10, random_state=42, n_jobs=1)
print(result.importances_mean)

[0.05969231 0.20238462 0.049     ]


In [39]:
hgb.score(test_input, test_target)

0.8723076923076923

In [ ]:
#히스토그램 기반 그레이디언트 부스팅의 회귀 버전은 HistGradientBoostingRegresoor 클래스에 구현되어 있다.
#가장 대표적인 라이브러리는 XGBoost이다.

In [43]:
!pip install xgboost

   ---------------------------------------- 0.0/72.0 MB ? eta -:--:--
   ---------------------------------------- 0.3/72.0 MB ? eta -:--:--
   --- ------------------------------------ 5.5/72.0 MB 17.7 MB/s eta 0:00:04
   ------ --------------------------------- 11.5/72.0 MB 25.7 MB/s eta 0:00:03
   ------ --------------------------------- 12.6/72.0 MB 16.8 MB/s eta 0:00:04
   ------------- -------------------------- 25.2/72.0 MB 26.1 MB/s eta 0:00:02
   ---------------- ----------------------- 29.4/72.0 MB 25.5 MB/s eta 0:00:02
   ----------------------- ---------------- 41.9/72.0 MB 30.3 MB/s eta 0:00:01
   ------------------------------ --------- 55.3/72.0 MB 34.5 MB/s eta 0:00:01
   ----------------------------------- ---- 64.0/72.0 MB 37.1 MB/s eta 0:00:01
   ------------------------------------ --- 65.3/72.0 MB 32.5 MB/s eta 0:00:01
   ---------------------------------------  71.3/72.0 MB 31.8 MB/s eta 0:00:01
   ---------------------------------------- 72.0/72.0 MB 29.4 MB/s  0:0

In [45]:
from xgboost import XGBClassifier
xgb = XGBClassifier(tree_method='hist',random_state=42)
scores = cross_validate(xgb, train_input, train_target, return_train_score=True, n_jobs=1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9567059184812372 0.8783915747390243


In [47]:
!pip install lightgbm

   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------------- 1.5/1.5 MB 25.3 MB/s  0:00:00


In [48]:
from lightgbm import LGBMClassifier
lgb = LGBMClassifier(random_state=42)
socres =cross_validate(lgb, train_input, train_target, return_train_score=True, n_jobs=1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

[LightGBM] [Info] Number of positive: 3151, number of negative: 1006
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000392 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 372
[LightGBM] [Info] Number of data points in the train set: 4157, number of used features: 3
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.757999 -> initscore=1.141738
[LightGBM] [Info] Start training from score 1.141738
[LightGBM] [Info] Number of positive: 3151, number of negative: 1006
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000062 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 370
[LightGBM] [Info] Number of data points in the train set: 4157, number of used features: 3
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.757999 -> initscore=1.141738
[LightGBM] [Info] Start training from score 1.141738
[LightGBM] [Info] Number o

In [ ]:
[사이킷런에서 제공하는 앙상블 학습 알고리즘]
- 랜덤 포레스트 : 부트스트랩 샘플 사용. 대표 앙상블 학습 알고리즘
- 엑스트라 트리: 결정 트리의 노드를 랜덤하게 분할함
- 그레이디언트 부스팅: 이전 트리의 손실을 보완하는 식으로 얕은 결정 트리를 연속하여 추가함
- 히스토그램 기반 그레이디언트 부스팅: 훈련데이터를 256개 정수 구간으로 나누어 빠르고 높은 성능을 냄